name: Main workflow

on:
  pull_request:
  push:
    branches:
      - "1.30"
      - "1.40" # for future
      - "1.50"
      - "more-dune"

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - 4.14.2

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam pin add Lama.dev . --no-action
      - run: opam depext Lama.dev --yes --with-test
      - run: opam install . --deps-only --with-test
      - run: eval $(opam env)
      - run: opam exec -- make
      - run: opam exec -- make regression
